import { parseAbi } from "viem";

/** Custom errors across Montane contracts, merged into every simulated call so reverts decode by name. */
export const protocolErrors = parseAbi([
  "error AlreadyClaimed()",
  "error BadCdp()",
  "error BadOrder()",
  "error BookFull()",
  "error Cap()",
  "error Circuit()",
  "error Closed()",
  "error EnforcedPause()",
  "error Exists()",
  "error FomoOrder()",
  "error FomoSilent()",
  "error Frozen()",
  "error HunterSelf()",
  "error HuntExists()",
  "error InactiveCdp()",
  "error InstantHunt()",
  "error InvalidOraclePrice()",
  "error MinRatio()",
  "error NoHunt()",
  "error NotFrostbite()",
  "error Nothing()",
  "error NothingToRedeem()",
  "error NotMaker()",
  "error NotMature()",
  "error NotParty()",
  "error NotResolved()",
  "error NotSettled()",
  "error NotVerdant()",
  "error RedeemClosed()",
  "error SelfMatch()",
  "error ShortCap()",
  "error ShortClosed()",
  "error SpreadTooTight()",
  "error TooEarly()",
  "error WindowClosed()",
  "error ZeroAmount()",
]);
